### ISSUE TITLE
Make easier to support multiple algos?

### ISSUE THREAD

**Issue by mamcx** [RustCrypto/password-hashes#245]
I try to support the selection of many algorithms to store passwords (like in django) and found it not as easy to do it. This crate has all in a workspace but not a way to select a group alike:

```toml
# Ideally:
password-hash = { version = "*",  features = ["argon2", "scrypt"] }

# Today
# All sub-crate reexport dependencies, so I need to manually re-add all?
argon2 = { version = "0.3", features = ["std"] ,  optional=true}
scrypt = {version = "0.8.0",  optional=true"}

# So I can do things generically...
password-hash = "*"
rand-core = "*"
```
